plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '4.0.4'
    id 'application'
}

mainClassName = 'CassandraInit'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
    implementation group: 'com.datastax.cassandra', name: 'cassandra-driver-core', version: '3.11.3'
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName = "CassandraProcessor"
    archiveClassifier = null
}
